name: shadcn_ui_widgetbook
description: "Widgetbook for shadcn_ui - a shadcn/ui ported to Flutter with awesome, fully customizable UI components."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shadcn_ui: ^0.36.1
  widgetbook: ^3.17.1
  widgetbook_annotation: ^3.7.0

dev_dependencies:
  build_runner: ^2.9.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  widgetbook_generator: ^3.17.0

flutter:
  uses-material-design: true
